name: 'udb'

services:
  udb:
    build:
      context: ../
      dockerfile: docker/be/Dockerfile
    hostname: udb.socialnetwork
    container_name: be-api
    depends_on:
      - cl1-udb1
    ports:
      - 5005:5005
      - 8080:8080
    expose:
      - 8080
    networks:
      - internal
    entrypoint: ["wait-for.sh", "/var/lib/appdata/init_done", "--"]
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "target/udb.jar"]
    volumes:
      - appdata-volume:/var/lib/appdata

  cl1-udb1:
    build:
      context: couchbase
      dockerfile: Dockerfile
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl1-udb
      - CLUSTER_NODES=cl1-udb2.socialnetwork,cl1-udb3.socialnetwork
      - XDCR_CLUSTER_NAME=cl2-udb
      - XDCR_CLUSTER_HOSTNAME=cl2-udb1.socialnetwork
    hostname: cl1-udb1.socialnetwork
    container_name: cl1-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8001-8006:8091-8096"
      - "11200-11201:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/cb-orchestrator.sh"
    volumes:
      - appdata-volume:/var/lib/appdata

  cl2-udb1:
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl2-udb
      - CLUSTER_NODES=cl2-udb2.socialnetwork,cl2-udb3.socialnetwork
      - XDCR_CLUSTER_NAME=cl1-udb
      - XDCR_CLUSTER_HOSTNAME=cl1-udb1.socialnetwork
    hostname: cl2-udb1.socialnetwork
    container_name: cl2-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8101-8106:8091-8096"
      - "11300-11301:11210-11211"
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/cb-orchestrator.sh"

  cl1-udb2:
    image: couchbase:latest
    hostname: cl1-udb2.socialnetwork
    container_name: cl1-udb2
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8011-8016:8091-8096"
      - "11210-11211:11210-11211"

  cl1-udb3:
    image: couchbase:latest
    hostname: cl1-udb3.socialnetwork
    container_name: cl1-udb3
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8021-8026:8091-8096"
      - "11220-11221:11210-11211"

  cl2-udb2:
    image: couchbase:latest
    hostname: cl2-udb2.socialnetwork
    container_name: cl2-udb2
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8111-8116:8091-8096"
      - "11310-11311:11210-11211"

  cl2-udb3:
    image: couchbase:latest
    hostname: cl2-udb3.socialnetwork
    container_name: cl2-udb3
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8121-8126:8091-8096"
      - "11320-11321:11210-11211"

networks:
  internal:
    driver: bridge

volumes:
  appdata-volume: