name: 'udb'

services:
  udb:
    build:
      context: ../
      dockerfile: docker/be/Dockerfile
    hostname: udb.socialnetwork
    container_name: udb-api
    ports:
      - 5005:5005
      - 8080:8080
    expose:
      - 8080
    networks:
      - internal
    entrypoint: ["wait-for.sh", "/var/lib/appdata/init_done", "--"]
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "target/udb.jar"]
    volumes:
      - appdata-volume:/var/lib/appdata
      - ../:/app
      - maven-repo:/root/.m2

  cl1-udb1:
    build:
      context: couchbase
      dockerfile: Dockerfile
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl1-udb
      - CLUSTER_NODES=cl1-udb2.socialnetwork,cl1-udb3.socialnetwork
      - XDCR_CLUSTER_NAME=cl2-udb
      - XDCR_CLUSTER_HOSTNAME=cl2-udb1.socialnetwork
      - MAIN=true
    hostname: cl1-udb1.socialnetwork
    container_name: cl1-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/tools/cb-orchestrator.sh"
    volumes:
      - appdata-volume:/var/lib/appdata

  cl2-udb1:
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl2-udb
      - CLUSTER_NODES=cl2-udb2.socialnetwork,cl2-udb3.socialnetwork
      - XDCR_CLUSTER_NAME=cl1-udb
      - XDCR_CLUSTER_HOSTNAME=cl1-udb1.socialnetwork
    hostname: cl2-udb1.socialnetwork
    container_name: cl2-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8191-8196:8091-8096"
      - "11310-11311:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/tools/cb-orchestrator.sh"

  cl1-udb2:
    image: couchbase:latest
    hostname: cl1-udb2.socialnetwork
    container_name: cl1-udb2
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8291-8296:8091-8096"
      - "11410-11411:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201

  cl1-udb3:
    image: couchbase:latest
    hostname: cl1-udb3.socialnetwork
    container_name: cl1-udb3
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8391-8396:8091-8096"
      - "11520-11521:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201

  cl2-udb2:
    image: couchbase:latest
    hostname: cl2-udb2.socialnetwork
    container_name: cl2-udb2
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8491-8496:8091-8096"
      - "11610-11611:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201

  cl2-udb3:
    image: couchbase:latest
    hostname: cl2-udb3.socialnetwork
    container_name: cl2-udb3
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8591-8596:8091-8096"
      - "11710-11711:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201

networks:
  internal:
    driver: bridge

volumes:
  appdata-volume:
  maven-repo:
