name: 'udb'

services:
  udb:
    build:
      context: ../
      dockerfile: docker/be/Dockerfile
    hostname: udb.socialnetwork
    container_name: udb-api
    ports:
      - 5005:5005
      - 8080:8080
    expose:
      - 8080
    networks:
      - internal
    entrypoint: ["wait-for.sh", "/var/lib/appdata/init_done", "--"]
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "target/udb.jar"]
    volumes:
      - appdata-volume:/var/lib/appdata
      - ../:/app
      - maven-repo:/root/.m2

  cl1-udb1:
    build:
      context: couchbase
      dockerfile: Dockerfile
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl1-udb
      - MAIN=true
    hostname: cl1-udb1.socialnetwork
    container_name: cl1-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8001-8006:8091-8096"
      - "11200-11201:11210-11211"
    expose:
      - 8091
      - 8092
      - 8093
      - 8094
      - 8095
      - 8096
      - 11200
      - 11201
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/tools/cb-orchestrator.sh"
    volumes:
      - appdata-volume:/var/lib/appdata

networks:
  internal:
    driver: bridge

volumes:
  appdata-volume:
  maven-repo:
