name: 'udb'

services:
  udb:
    build:
      context: ../
      dockerfile: docker/be/Dockerfile
    hostname: udb.socialnetwork
    container_name: udb-api
    ports:
      - 5005:5005
      - 8080:8080
    expose:
      - 8080
    networks:
      - internal
    entrypoint: ["wait-for.sh", "/var/lib/appdata/init_done", "--"]
    # TODO: FIX THIS, SHOULD POINT TO ROOT NOT TO MODULE
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "modules/base.application/target/base.application.jar"]
    volumes:
      - appdata-volume:/var/lib/appdata
      - ../:/app
      - maven-repo:/root/.m2

  cl1-udb1:
    build:
      context: couchbase
      dockerfile: Dockerfile
    image: udb-couchbase-cluster:latest
    pull_policy: never
    env_file:
      - couchbase/cb.env
    environment:
      - CLUSTER_NAME=cl1-udb
      - MAIN=true
    hostname: cl1-udb1.socialnetwork
    container_name: cl1-udb1
    working_dir: /opt/couchbase
    stdin_open: true
    tty: true
    networks:
      - internal
    ports:
      - "8091-8096:8091-8096"
      - "11210-11211:11210-11211"
    expose:
      - 8001
      - 8002
      - 8003
      - 8004
      - 8005
      - 8006
      - 11200
      - 11201
    entrypoint: [ "" ]
    command: sh -c "/opt/couchbase/init/tools/cb-orchestrator.sh"
    volumes:
      - appdata-volume:/var/lib/appdata

networks:
  internal:
    driver: bridge

volumes:
  appdata-volume:
  maven-repo:
